#ifndef ESP32_WIFI_ONEWIRE_MQTT_MAIN_INCLUDE_NON_VOLATILE_STORAGE_H_
#define ESP32_WIFI_ONEWIRE_MQTT_MAIN_INCLUDE_NON_VOLATILE_STORAGE_H_

#include "esp_err.h"

esp_err_t nvs_init(void);

#endif  // ESP32_WIFI_ONEWIRE_MQTT_MAIN_INCLUDE_NON_VOLATILE_STORAGE_H_
