#ifndef ESP32_WIFI_ONEWIRE_MQTT_MAIN_INCLUDE_TYPES_H_
#define ESP32_WIFI_ONEWIRE_MQTT_MAIN_INCLUDE_TYPES_H_

typedef enum {
    PRIORITY_IDLE = 0,
    PRIORITY_LOWEST,
    PRIORITY_LOW,
    PRIORITY_MIDDLE,
    PRIORITY_HIGH,
    PRIORITY_MAX,
} task_priority_t;

#endif  // ESP32_WIFI_ONEWIRE_MQTT_MAIN_INCLUDE_TYPES_H_
