#ifndef ESP32_WIFI_ONEWIRE_MQTT_MAIN_INCLUDE_WIFI_H_
#define ESP32_WIFI_ONEWIRE_MQTT_MAIN_INCLUDE_WIFI_H_

#include "esp_err.h"

esp_err_t wifi_init(void);

#endif  // ESP32_WIFI_ONEWIRE_MQTT_MAIN_INCLUDE_WIFI_H_
